--
-- PostgreSQL database dump
--

\restrict F2RDS0xtHTbS0bIN18ko2eXJvtlzcquffBsKxTAUAgjgBpdjnfwRmbn0hAyXhwz

-- Dumped from database version 18.3
-- Dumped by pg_dump version 18.3

-- Started on 2026-03-10 22:09:51

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 220 (class 1259 OID 16390)
-- Name: departamentos; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.departamentos (
    id bigint NOT NULL,
    descripcion character varying(255),
    nombre character varying(255)
);


ALTER TABLE public.departamentos OWNER TO postgres;

--
-- TOC entry 219 (class 1259 OID 16389)
-- Name: departamentos_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.departamentos ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.departamentos_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 222 (class 1259 OID 16399)
-- Name: empleados; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.empleados (
    id bigint NOT NULL,
    apellido character varying(255) NOT NULL,
    correo character varying(255) NOT NULL,
    nombre character varying(255) NOT NULL,
    salario double precision NOT NULL,
    departamento_id bigint,
    CONSTRAINT empleados_salario_check CHECK ((salario >= (1)::double precision))
);


ALTER TABLE public.empleados OWNER TO postgres;

--
-- TOC entry 221 (class 1259 OID 16398)
-- Name: empleados_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.empleados ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.empleados_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 5015 (class 0 OID 16390)
-- Dependencies: 220
-- Data for Name: departamentos; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.departamentos (id, descripcion, nombre) FROM stdin;
1	Departamento encargado de la innovación y desarrollo de tecnologías de la información.	Departamento de Tecnologia
3	Departamento encargado de recursos humanos	Departamento de recursos humanos
\.


--
-- TOC entry 5017 (class 0 OID 16399)
-- Dependencies: 222
-- Data for Name: empleados; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.empleados (id, apellido, correo, nombre, salario, departamento_id) FROM stdin;
1	Pérez	juan.perez@example.com	Juan	5000000	1
\.


--
-- TOC entry 5023 (class 0 OID 0)
-- Dependencies: 219
-- Name: departamentos_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.departamentos_id_seq', 3, true);


--
-- TOC entry 5024 (class 0 OID 0)
-- Dependencies: 221
-- Name: empleados_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.empleados_id_seq', 1, true);


--
-- TOC entry 4863 (class 2606 OID 16397)
-- Name: departamentos departamentos_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.departamentos
    ADD CONSTRAINT departamentos_pkey PRIMARY KEY (id);


--
-- TOC entry 4865 (class 2606 OID 16411)
-- Name: empleados empleados_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.empleados
    ADD CONSTRAINT empleados_pkey PRIMARY KEY (id);


--
-- TOC entry 4866 (class 2606 OID 16412)
-- Name: empleados fk1dvvcamb3oxb2d9xqd9taug0u; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.empleados
    ADD CONSTRAINT fk1dvvcamb3oxb2d9xqd9taug0u FOREIGN KEY (departamento_id) REFERENCES public.departamentos(id);


-- Completed on 2026-03-10 22:09:51

--
-- PostgreSQL database dump complete
--

\unrestrict F2RDS0xtHTbS0bIN18ko2eXJvtlzcquffBsKxTAUAgjgBpdjnfwRmbn0hAyXhwz

